# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.define "Ctrl-A-EES"
  config.vm.hostname = "Ctrl-A-EES"
  config.vm.provider "virtualbox" do |v|
    v.cpus = 4
    v.memory = 12*1024
    v.name = "Ctrl-A-EES"
  end

  config.vm.network "forwarded_port", guest: 22, host: 3022
  config.vm.network "public_network"

  config.vm.provision "shell", reset: false, inline: <<-SHELL
    apt-get install net-tools -y
    apt-get install python3 -y
    apt-get install python3-pip -y
    apt-get install git -y
    apt-get install apache2 -y
    apt-get install php -y
    sudo service apache2 restart
    cd /var/www/html && sudo git clone https://github.com/mwong4/Ctrl-A-Electronic-Election_System.git
    sudo rm /var/www/html/index.html
    sudo mv /var/www/html/Ctrl-A-Electronic-Election_System/index.html /var/www/html/index.html
    ifconfig | grep inet | grep netmask | awk '{print $2}'
  SHELL

end
